// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/20/2026, 9:45:14 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["D:/laragon/www/data-marketplace/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/laragon/www/data-marketplace/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/laragon/www/data-marketplace/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/laragon/www/data-marketplace/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/laragon/www/data-marketplace/frontend/plugins/**/*.{js,ts,mjs}","D:/laragon/www/data-marketplace/frontend/composables/**/*.{js,ts,mjs}","D:/laragon/www/data-marketplace/frontend/utils/**/*.{js,ts,mjs}","D:/laragon/www/data-marketplace/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/laragon/www/data-marketplace/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/laragon/www/data-marketplace/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/laragon/www/data-marketplace/frontend/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;