"""p5b_collection_dispatch_entries

Revision ID: 2a6bbcd2e938
Revises: f82c4d855f09
Create Date: 2026-06-20 19:59:40.114450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a6bbcd2e938'
down_revision: Union[str, Sequence[str], None] = 'f82c4d855f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_dispatches',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('submission_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['user_auth.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['data_requests.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dispatch_request', 'collection_dispatches', ['request_id'], unique=False)
    op.create_table('collection_entries',
    sa.Column('dispatch_id', sa.UUID(), nullable=False),
    sa.Column('contributor_ref', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('geo_lat', sa.Float(), nullable=True),
    sa.Column('geo_lng', sa.Float(), nullable=True),
    sa.Column('photo_ref', sa.String(), nullable=True),
    sa.Column('consent_basis', sa.String(), nullable=True),
    sa.Column('lawful_basis', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dispatch_id'], ['collection_dispatches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entry_dispatch', 'collection_entries', ['dispatch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_entry_dispatch', table_name='collection_entries')
    op.drop_table('collection_entries')
    op.drop_index('idx_dispatch_request', table_name='collection_dispatches')
    op.drop_table('collection_dispatches')
    # ### end Alembic commands ###
