"""s4a_submission_quarantine_pii

Revision ID: 431b51c7dfce
Revises: 8cacc4229083
Create Date: 2026-06-20 19:19:01.160827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431b51c7dfce'
down_revision: Union[str, Sequence[str], None] = '8cacc4229083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('quarantined', sa.Boolean(), nullable=True))
    op.add_column('submissions', sa.Column('pii_report', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'pii_report')
    op.drop_column('submissions', 'quarantined')
    # ### end Alembic commands ###
