"""p4b_purchases_ledger

Revision ID: 52545c08371e
Revises: 571aef03d325
Create Date: 2026-06-20 19:41:59.611733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52545c08371e'
down_revision: Union[str, Sequence[str], None] = '571aef03d325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchases',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('storage_location', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['user_auth.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_purchase_buyer', 'purchases', ['buyer_id'], unique=False)
    op.add_column('ledger', sa.Column('purchase_id', sa.UUID(), nullable=True))
    op.alter_column('ledger', 'request_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('idx_ledger_purchase_id', 'ledger', ['purchase_id'], unique=False)
    op.create_foreign_key(None, 'ledger', 'purchases', ['purchase_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ledger', type_='foreignkey')
    op.drop_index('idx_ledger_purchase_id', table_name='ledger')
    op.alter_column('ledger', 'request_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('ledger', 'purchase_id')
    op.drop_index('idx_purchase_buyer', table_name='purchases')
    op.drop_table('purchases')
    # ### end Alembic commands ###
