"""p4a_listings

Revision ID: 571aef03d325
Revises: d6f267ce3037
Create Date: 2026-06-20 19:37:34.757564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '571aef03d325'
down_revision: Union[str, Sequence[str], None] = 'd6f267ce3037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('price_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('validated_amount', sa.Integer(), nullable=False),
    sa.Column('required_format', sa.String(), nullable=True),
    sa.Column('spec', sa.JSON(), nullable=True),
    sa.Column('license_id', sa.UUID(), nullable=True),
    sa.Column('provenance', sa.Text(), nullable=True),
    sa.Column('sample', sa.JSON(), nullable=True),
    sa.Column('dataset_hash', sa.String(), nullable=True),
    sa.Column('storage_location', sa.String(), nullable=True),
    sa.Column('key_hashes', sa.JSON(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('pii_report', sa.JSON(), nullable=True),
    sa.Column('quarantined', sa.Boolean(), nullable=True),
    sa.Column('owner_signature', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'SOLD_OUT', 'TAKEN_DOWN', name='listing_status_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['user_auth.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_listing_status', 'listings', ['status', 'is_deleted'], unique=False)
    op.create_index('idx_listing_supplier', 'listings', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_listing_supplier', table_name='listings')
    op.drop_index('idx_listing_status', table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
