"""add_accepted_at_to_submissions

Revision ID: 63ef5eb6f4b0
Revises: f62dba7daa59
Create Date: 2026-06-19 15:17:05.056323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ef5eb6f4b0'
down_revision: Union[str, Sequence[str], None] = 'f62dba7daa59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('accepted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'accepted_at')
    # ### end Alembic commands ###
