"""s3_account_security_columns

Revision ID: 8cacc4229083
Revises: 56b389a8527d
Create Date: 2026-06-20 16:11:42.342176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cacc4229083'
down_revision: Union[str, Sequence[str], None] = '56b389a8527d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.add_column('user_auth', sa.Column('payout_account_changed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_auth', 'payout_account_changed_at')
    op.drop_column('user_auth', 'locked_until')
    # ### end Alembic commands ###
