"""h4_mfa

Revision ID: a871b7fb4fa7
Revises: f2d8737a9cda
Create Date: 2026-06-21 14:22:18.499322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a871b7fb4fa7'
down_revision: Union[str, Sequence[str], None] = 'f2d8737a9cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth', sa.Column('mfa_secret', sa.String(), nullable=True))
    op.add_column('user_auth', sa.Column('mfa_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_auth', 'mfa_enabled')
    op.drop_column('user_auth', 'mfa_secret')
    # ### end Alembic commands ###
