"""add_accepted_keys_and_submission_key_hashes

Revision ID: c1cebd6bb551
Revises: 63ef5eb6f4b0
Create Date: 2026-06-19 15:19:34.145752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1cebd6bb551'
down_revision: Union[str, Sequence[str], None] = '63ef5eb6f4b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accepted_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['data_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'key_hash', name='uq_accepted_key')
    )
    op.create_index('idx_accepted_keys_request', 'accepted_keys', ['request_id'], unique=False)
    op.add_column('submissions', sa.Column('key_hashes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'key_hashes')
    op.drop_index('idx_accepted_keys_request', table_name='accepted_keys')
    op.drop_table('accepted_keys')
    # ### end Alembic commands ###
