"""p7b_request_category

Revision ID: ce0b3114c871
Revises: e4b4cd7d584b
Create Date: 2026-06-21 13:55:40.232125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce0b3114c871'
down_revision: Union[str, Sequence[str], None] = 'e4b4cd7d584b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_requests', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_requests', 'category')
    # ### end Alembic commands ###
