"""p7a_commission_amount

Revision ID: e4b4cd7d584b
Revises: ae38be698516
Create Date: 2026-06-21 13:52:08.010563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4b4cd7d584b'
down_revision: Union[str, Sequence[str], None] = 'ae38be698516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('commission_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('submissions', sa.Column('commission_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'commission_amount')
    op.drop_column('purchases', 'commission_amount')
    # ### end Alembic commands ###
