"""h2_audit_log

Revision ID: f2d8737a9cda
Revises: ce0b3114c871
Create Date: 2026-06-21 14:16:49.562173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d8737a9cda'
down_revision: Union[str, Sequence[str], None] = 'ce0b3114c871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('object_id', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_log', ['action'], unique=False)
    op.create_index('idx_audit_object', 'audit_log', ['object_type', 'object_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_object', table_name='audit_log')
    op.drop_index('idx_audit_action', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
