"""p5a_request_collect_mode

Revision ID: f82c4d855f09
Revises: 52545c08371e
Create Date: 2026-06-20 19:57:14.789049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82c4d855f09'
down_revision: Union[str, Sequence[str], None] = '52545c08371e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_requests', sa.Column('mode', sa.String(), nullable=True))
    op.add_column('data_requests', sa.Column('collection_spec', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_requests', 'collection_spec')
    op.drop_column('data_requests', 'mode')
    # ### end Alembic commands ###
